CREATE TABLE "offense_cases" (
	"seizureId" varchar(255) PRIMARY KEY NOT NULL,
	"caseNumber" integer,
	"actionDate" date,
	"articleId" integer NOT NULL,
	"articleNumber" varchar(50) NOT NULL,
	"offenderId" varchar(255) NOT NULL,
	"offenderName" varchar(255) NOT NULL,
	"offenderFatherName" varchar(255) NOT NULL,
	"nationalIdNumber" varchar(100) NOT NULL,
	"offenderAddress" varchar(255) NOT NULL,
	"offenderCreatedAt" timestamp NOT NULL,
	"offenderUpdatedAt" timestamp NOT NULL,
	"offenseId" integer NOT NULL,
	"offenseName" varchar(255) NOT NULL,
	"officerId" integer NOT NULL,
	"officerName" varchar(255) NOT NULL,
	"fineAmount" varchar(50) NOT NULL,
	"finePaid" varchar(50),
	"vehicleId" varchar(255) NOT NULL,
	"vehicleNumber" varchar(100) NOT NULL,
	"vehicleTypes" varchar(100) NOT NULL,
	"vehicleLicenseNumber" varchar(100),
	"vehicleCategoriesId" integer NOT NULL,
	"vehicleCreatedAt" timestamp NOT NULL,
	"vehicleUpdatedAt" timestamp NOT NULL,
	"offenderVehicleId" varchar(255) NOT NULL,
	"offenderVehicleCreatedAt" timestamp NOT NULL,
	"offenderVehicleUpdatedAt" timestamp NOT NULL,
	"seizedDate" date NOT NULL,
	"seizedItemId" integer NOT NULL,
	"seizedItemName" varchar(255) NOT NULL,
	"seizureLocation" varchar(255) NOT NULL,
	"seizureCreatedAt" timestamp NOT NULL,
	"seizureUpdatedAt" timestamp NOT NULL,
	"disciplinaryCommittedId" integer NOT NULL,
	"dcCreatedAt" timestamp NOT NULL,
	"dcUpdatedAt" timestamp NOT NULL,
	"wheelTax" varchar(100)
);
